### PR TITLE
added support for an AppendCacheBustSpriteSuffix parameter as per issue #6

### PR DESCRIPTION
**Pull request by Driedas**
implemented sprite cache busting feature as per issue #6

### CODE REVIEW

**Comment by madskristensen** [comment]
Awesome. Thanks

**Comment by Driedas** [comment]
thanks for the super quick turnaround and an awesome tool in the first place!

**Comment by madskristensen** [comment]
Thank you!!

Try out the CI build here http://vsixgallery.com/extension/cd92c0c6-2c32-49a3-83ca-0dc767c7d78e/

**Comment by Driedas** [comment]
Hey,
have just downloaded the CI build and tried to install however got this error (username replaced with foobar):
```
02.02.2018 8:46:28 - Microsoft VSIX Installer
02.02.2018 8:46:28 - -------------------------------------------
02.02.2018 8:46:28 - vsixinstaller.exe version:
02.02.2018 8:46:28 - 15.5.99+g87f89a485e
02.02.2018 8:46:28 - -------------------------------------------
02.02.2018 8:46:28 - Command line parameters:
02.02.2018 8:46:28 - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\foobar\Downloads\Image Sprites v1.4.52.vsix
02.02.2018 8:46:28 - -------------------------------------------
02.02.2018 8:46:28 - Microsoft VSIX Installer
02.02.2018 8:46:28 - -------------------------------------------
02.02.2018 8:46:32 - Initializing Install...
02.02.2018 8:46:32 - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionPackageException: The file is not a valid VSIX package.
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Pull request merged**
